/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketplacePageRouteImport } from './routes/marketplace.$page'
import { Route as MarketplaceVendorIdRouteImport } from './routes/marketplace.vendor.$id'
import { Route as MarketplaceProductIdRouteImport } from './routes/marketplace.product.$id'
import { Route as MarketplacePartnerSlugRouteImport } from './routes/marketplace.partner.$slug'
import { Route as MarketplaceIndustrySlugRouteImport } from './routes/marketplace.industry.$slug'
import { Route as MarketplaceCategorySlugRouteImport } from './routes/marketplace.category.$slug'

const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplacePageRoute = MarketplacePageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceVendorIdRoute = MarketplaceVendorIdRouteImport.update({
  id: '/vendor/$id',
  path: '/vendor/$id',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceProductIdRoute = MarketplaceProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplacePartnerSlugRoute = MarketplacePartnerSlugRouteImport.update({
  id: '/partner/$slug',
  path: '/partner/$slug',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceIndustrySlugRoute = MarketplaceIndustrySlugRouteImport.update({
  id: '/industry/$slug',
  path: '/industry/$slug',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceCategorySlugRoute = MarketplaceCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => MarketplaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/marketplace/$page': typeof MarketplacePageRoute
  '/marketplace/category/$slug': typeof MarketplaceCategorySlugRoute
  '/marketplace/industry/$slug': typeof MarketplaceIndustrySlugRoute
  '/marketplace/partner/$slug': typeof MarketplacePartnerSlugRoute
  '/marketplace/product/$id': typeof MarketplaceProductIdRoute
  '/marketplace/vendor/$id': typeof MarketplaceVendorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/marketplace/$page': typeof MarketplacePageRoute
  '/marketplace/category/$slug': typeof MarketplaceCategorySlugRoute
  '/marketplace/industry/$slug': typeof MarketplaceIndustrySlugRoute
  '/marketplace/partner/$slug': typeof MarketplacePartnerSlugRoute
  '/marketplace/product/$id': typeof MarketplaceProductIdRoute
  '/marketplace/vendor/$id': typeof MarketplaceVendorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/marketplace/$page': typeof MarketplacePageRoute
  '/marketplace/category/$slug': typeof MarketplaceCategorySlugRoute
  '/marketplace/industry/$slug': typeof MarketplaceIndustrySlugRoute
  '/marketplace/partner/$slug': typeof MarketplacePartnerSlugRoute
  '/marketplace/product/$id': typeof MarketplaceProductIdRoute
  '/marketplace/vendor/$id': typeof MarketplaceVendorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/marketplace'
    | '/marketplace/$page'
    | '/marketplace/category/$slug'
    | '/marketplace/industry/$slug'
    | '/marketplace/partner/$slug'
    | '/marketplace/product/$id'
    | '/marketplace/vendor/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/marketplace'
    | '/marketplace/$page'
    | '/marketplace/category/$slug'
    | '/marketplace/industry/$slug'
    | '/marketplace/partner/$slug'
    | '/marketplace/product/$id'
    | '/marketplace/vendor/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/marketplace'
    | '/marketplace/$page'
    | '/marketplace/category/$slug'
    | '/marketplace/industry/$slug'
    | '/marketplace/partner/$slug'
    | '/marketplace/product/$id'
    | '/marketplace/vendor/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$page': {
      id: '/marketplace/$page'
      path: '/$page'
      fullPath: '/marketplace/$page'
      preLoaderRoute: typeof MarketplacePageRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/vendor/$id': {
      id: '/marketplace/vendor/$id'
      path: '/vendor/$id'
      fullPath: '/marketplace/vendor/$id'
      preLoaderRoute: typeof MarketplaceVendorIdRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/product/$id': {
      id: '/marketplace/product/$id'
      path: '/product/$id'
      fullPath: '/marketplace/product/$id'
      preLoaderRoute: typeof MarketplaceProductIdRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/partner/$slug': {
      id: '/marketplace/partner/$slug'
      path: '/partner/$slug'
      fullPath: '/marketplace/partner/$slug'
      preLoaderRoute: typeof MarketplacePartnerSlugRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/industry/$slug': {
      id: '/marketplace/industry/$slug'
      path: '/industry/$slug'
      fullPath: '/marketplace/industry/$slug'
      preLoaderRoute: typeof MarketplaceIndustrySlugRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/category/$slug': {
      id: '/marketplace/category/$slug'
      path: '/category/$slug'
      fullPath: '/marketplace/category/$slug'
      preLoaderRoute: typeof MarketplaceCategorySlugRouteImport
      parentRoute: typeof MarketplaceRoute
    }
  }
}

interface MarketplaceRouteChildren {
  MarketplacePageRoute: typeof MarketplacePageRoute
  MarketplaceCategorySlugRoute: typeof MarketplaceCategorySlugRoute
  MarketplaceIndustrySlugRoute: typeof MarketplaceIndustrySlugRoute
  MarketplacePartnerSlugRoute: typeof MarketplacePartnerSlugRoute
  MarketplaceProductIdRoute: typeof MarketplaceProductIdRoute
  MarketplaceVendorIdRoute: typeof MarketplaceVendorIdRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplacePageRoute: MarketplacePageRoute,
  MarketplaceCategorySlugRoute: MarketplaceCategorySlugRoute,
  MarketplaceIndustrySlugRoute: MarketplaceIndustrySlugRoute,
  MarketplacePartnerSlugRoute: MarketplacePartnerSlugRoute,
  MarketplaceProductIdRoute: MarketplaceProductIdRoute,
  MarketplaceVendorIdRoute: MarketplaceVendorIdRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
